class LoginPageLocators
TOOLBAR_OK = '//*[@class="toolbar_logo_img"]'
LOGIN_FIELD = '//*[@id="field_email"]'
PASSWORD_FILED = '//*[@type="password"]'
IN_OK = '//*[@data-l="t,sign_in"]'
IN_QR = '//*[@data-l="t,get_qr"]'
LOGIN_FOGOT = '//*[@data-l="t,restore"]'
REGISTRATION = '//*[@data-l="t,register"]'
ICON_VK='//*[@class="i ic social-icon __s __vk_id"]'
ICON_MAIL='//*[@class="i ic social-icon __s __mailru"]'
ICON_GO='//*[@class="i ic social-icon __s __gp"]'
ICON_YA='//*[@class="i ic social-icon __s __yandex"]'
ICON_APPLE='//*[@class="i ic social-icon __s __apple"]'
TOOLBAR_NAV = '//*[@class="toolbar_nav_i_ic"]'