class LoginPageLocators
TOOLBAR_OK = '//*[@class="toolbar_logo_img"]'
LOGIN_FIELD = '//*[@id="field_email"]'
PASSWORD_FILED = '//*[@type="password"]'
IN_OK = '//*[@data-l="t,sign_in"]'
IN_QR = '//*[@data-l="t,get_qr"]'
LOGIN_FOGOT = '//*[@data-l="t,restore"]'
REGISTRATION = '//*[@data-l="t,register"]'
ICON_VK='//*[@data-l="t,vkc"]'
ICON_MAIL='//*[@data-l="t,mailru"]'
ICON_GO='//*[@data-l="t,google"]'
ICON_YA='//*[@data-l="t,yandex"]'
ICON_APPLE='//*[@data-l="t,apple"]'
TOOLBAR_NAV = '//*[@class="toolbar_nav_a toolbar_nav_a__vk_ecosystem __a11y"]'