class LoginPageLocators
TOOLBAR_OK = '//*[@class="toolbar_logo_img"]'
LOGIN_FIELD = '//*[@id="field_email"]'
PASSWORD_FILED = '//*[@type="password"]'
IN_OK = '//*[@value="Войти в Одноклассники"]'
IN_QR = '//*[@class="qr-button-label"]'
LOGIN_FOGOT = '//*[@href="/dk?st.cmd=anonymRecoveryStart&st._aid=LeftColumn_Login_ForgotPassword"]'
REGISTRATION = '//*[@class="button-pro __sec mb-3x"]'
ICON_VK='//*[@class="i ic social-icon __s __vk_id"]'
ICON_MAIL='//*[@class="i ic social-icon __s __mailru"]'
ICON_GO='//*[@class="i ic social-icon __s __gp"]'
ICON_YA='//*[@class="i ic social-icon __s __yandex"]'
ICON_APPLE='//*[@class="i ic social-icon __s __apple"]'
TOOLBAR_NAV = '//*[@class="toolbar_nav_i_ic"]'